language: node_js
node_js:
- node
- lts/*
cache:
  directories:
  - "~/.npm"
before_install:
- echo -e "machine github.com\n login $CI_USER_TOKEN"
  >> ~/.netrc
before_script:
- bundle install
- npm install -g expo-cli
- npm i -g npm@latest
script:
- npm install -g expo-cli
- npm ci
- npx jest --ci
jobs:
  include:
  - stage: deploy
    if: branch = 172-deploy
    node_js: lts/*
    script:
    - npm ci
    - npm install -g expo-cli
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - "./deploy"
env:
  global:
  - secure: OhIa8Lt4lYM+CRqFWCxV5m5WA5WoLaPJQMYg5aqlfNSn11xV1thxsmhSAR+eHrfprz9qFxSPK3UlaUB47xRTMDEcLev+8COIAJw9PZmzlRqfQnzeHveJkBQjhW7Lf5c+KNrtriw34Bdkw9oavYC6TDkGeLFNQneeUWRSsQg6xIrjqKEI3+z8pVP6YIJEClHqfo6KbkTSYw2UKnGeFM9+3c16a+hsJKe1Phd004KO3lkntoXMWFxG7E2D/ofyOiKr9gsWReX4EviCy11lI6qr8RY38NZ5pEtIzPqxjdH8ozPu+4f9NjVNw+9Wn7tUveXOQbLMhxiaJHyZmML1+kuJANFtj4TtfIG0UPASOrPzc0FfZNljfvC35HquKR1XpDP5m7L4l4HAjBdYQ+VY3DBw9SxyTtEjCbVkPH8H6kyezHE+x3A3wNBXuAngflextjoNrUz1f6j2bTt7f9p9PYH7S6YSNM6+qWQkzIbYthQj4fUPvFEedLLle8SWyMb8hMriVN3NZsmeoY/IRjqPdv3wQPigdhvtn5ErZ60mXsfZ47FflAhksMSOo/PiGUYF5O/bAgA4nyRQh9rKn1F+Xy7oYo92DS5Hb7K+WVf1J5If4d0WcEuj204ebr/fwZ1osdP4eXMwDXHWdLxrmmUDKxvIBcFRFEPGKETxm9w+JOrHWR0=
  - secure: eRViLAwvpyyVa9TWMxB9nKfTnRgeO8qheOozoccE5osCSIL9mNWRSJiKErn3AnZ9aSChOXC+MVld/qttfIDSoR0G0y+ISY9wK6nkEqA0iYqNdRAEKZtgH92lDw9z4fVaWibeoLEbb+IVw8ma48mv26YFBOe6z4GxY65R2V+3nsPwa8HxrJ47hiZWxQKmfyqV8V970psSTAdMWEnYzqJgFBkMK0j7601IHmK9E5nvFdkVIyajxHSxlpNW574+ntHhxuZU7h8qu2zw6eD4JlTwIsiBnK5eD9ab403ssHWwXqfEx6yjF155rjSt8678UTuuqP/taraXEuPVgFWvzPlsn3DCPZeOzb8Mva4V59OEHyO7xN0oUV68ZAb6bqBoj/NnSJyr4nd2Wabzrf1amYIVeOzRfoSAXXJoXJiD7wrrTobsMq7+d99qY//viFT6wzmioSz4hCX7FErqbLsOuyeppMXxRwvJtQYIIFpZSN9Ds+XJ7FVHnIIh5hCT5Zz61qEA1VqiNxoRc6p3uaequ3diMoHfdLV7vPVYscEaT1lXOWv0K1I6ueIpCJhIlrj10Brq3A6qASr85t7WQohfg/mvxD7dBzpiaY/Y1VGgK2s6TsOOsii5Zy+EYgHqUv6rBUcOFddpkEn+afbo65wHbLbC2VVtNEDzfH6AotFUi2GfMx0=
  - secure: dMIOJ0blhILLjmo2ajUmsK5fEfCa6FmlZSuXnTM2mHN26ZkvjimwqtETWintBSYOuyxEpvrj+A3uNCDiuEdIWe31z/zHJTCyFiy9Hq6jBzx184gxOxbANCXtU6QXxFgozt9h+p4UPOEpPkTsDqwImZmYabDmozNto/TIqTsKicHAoMXWTwD5Q3hUlVv7bILTLKCQOvCpylEtk6+rp76Gbk4lbqtHrcha+ScmIq45zRXn06TwtvUXQRAZVXUNyEJjXfrKsxsmEVNea/kZlyTjia7LTqZOuexl/3K9vrzK6DPjT53krf1n4l+KDHmLZ65xb7ZTlg/h3jafCE9PUXUIeg51gU2P2PmbcxojZerJnoPuDkOTeHTIe2Xebutgc+oB11pGnr9p0j4nuDMYcpcb70X8GkoKjT+bPj6O7HG0/IYgzNtWHcYQpGo/18fPJwn+m1z74N+kljTJMC021nX8SpGTnYF6OyEBTq/AOkhO3dBeNyqg0pzUCMAE0kA6qrZ96yEIzADovvjWuCpd8v3lSosK+jdDiOS9hMFpr+7nU1eEXA4Ojle5hjEs/3UWiQVkLzlgCajffPRcFjcVPxHzAN2w69RZyT2WY+Yud0I2dQNvN30bTAs1Y1r6/lIM4asWkbpjJoBsN4uRr0g5N4flu1B/IJEVy31DRzGG4r9sxX8=
