language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_install:
  - echo -e "machine github.com\n  login $APPLE_USERNAME\n  password $CI_USER_PASSWORD" >> ~/.netrc
before_script:
  - bundle install
  - npm i -g npm@latest
  - npm i -g exp
script:
  - npm ci
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - ./deploy
