---
  os: osx
  language: node_js
  osx_image: xcode10.1
  node_js:
    - node
    - lts/*
  cache:
    directories:
      - "~/.npm"
  before_install:
    - gem update --system
    - echo -e "machine github.com\n  login $APPLE_USERNAME\n  password $CI_USER_PASSWORD" >> ~/.netrc
  before_script:
    - bundle update
    - bundle install
    - npm i -g npm@latest
  script:
    - npm ci
    - npx jest --ci
  jobs:
    include:
      - stage: deploy
        if: branch = 172-deploy
        node_js: lts/*
        script:
          - npm install
          - npm ci
          - npm install -g expo-cli
          - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          - fastlane setup_env
          - expo publish --release-channel production --non-interactive
          - expo build:ios --release-channel production --non-interactive --no-publish
          - curl -o app.ipa "$(expo url:ipa --non-interactive)"
          - fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata